# Check the Julia calculations in examples/, which the document shows verbatim,
# their connection to the thermal response, and regenerate the comparison tables.
using LinearAlgebra, Test, Printf
include(joinpath(@__DIR__, "..", "src", "SensitivityComparison.jl"))
using .SensitivityComparison

# Run an example script in its own module, so names such as H or Dual cannot
# collide, and return the module for inspecting its results.
function run_example(name)
    m = Core.eval(Main, Expr(:module, true, gensym(name), Expr(:block)))
    redirect_stdout(devnull) do
        Base.include(m, joinpath(@__DIR__, "..", "examples", name))
    end
    return m
end

function latex_number(x, digits)
    # Suppress signed zero in the displayed matrices.
    return iszero(x) ? "0" : Printf.format(Printf.Format("%.$(digits)f"), x)
end

function latex_result(x::Number)
    return latex_number(x, 12)
end

function latex_result(X::AbstractMatrix)
    rows = [join(latex_number.(X[i, :], 6), " & ") for i in axes(X, 1)]
    return raw"\begin{bmatrix}" * join(rows, "\\\\") * raw"\end{bmatrix}"
end

function latex_error(x, digits=2)
    mantissa, exponent = split(Printf.format(Printf.Format("%.$(digits)e"), x), 'e')
    return mantissa * raw"\times10^{" * string(parse(Int, exponent)) * "}"
end

# 256-bit reference for the thermal response: exp(tH)z by scaling and squaring a
# Taylor series, and its timestep derivative H exp(tH)z. H is built here from the
# documented formula, independently of the implementation.
function thermal_reference(A, B, e, x, u, dt)
    setprecision(BigFloat, 256) do
        n, nu = size(B)
        H = BigFloat.([A B Matrix(1.0I, n, n); zeros(nu+n, 2n+nu)])
        z = BigFloat.(vcat(x, u, e))
        M = BigFloat(dt)*H
        s = max(0, ceil(Int, log2(opnorm(Float64.(M), 1))) + 4)
        Ms = M/BigFloat(2)^s
        E = Matrix{BigFloat}(I, size(M))
        P = copy(E)
        for k in 1:40
            P = P*Ms/k
            E += P
        end
        for _ in 1:s
            E = E*E
        end
        (E*z)[1:n], (H*E*z)[1:n]
    end
end

function write_thermal_comparison(value, derivative, ctse, cr)
    relerr(a, b) = Float64.(abs.(BigFloat.(a) .- b) ./ abs.(b))
    errors = [relerr(ctse[1], value), relerr(ctse[2], derivative),
              relerr(cr[1], value), relerr(cr[2], derivative)]
    open(joinpath(@__DIR__, "thermal_comparison.tex"), "w") do io
        println(io, "% Generated by verify_ctse_dual_cr_examples.jl; do not edit by hand.")
        println(io, raw"\begin{center}\small")
        println(io, raw"\begin{tabular}{rrrcccc}")
        println(io, raw"\toprule")
        println(io, raw" & & & \multicolumn{2}{c}{CTSE relative error} & \multicolumn{2}{c}{Dual CR relative error}" * "\\\\")
        println(io, raw"\cmidrule(lr){4-5}\cmidrule(lr){6-7}")
        println(io, raw"Voxel & $R_i(t)$ [K] & $R_i'(t)$ [K/s] & $R_i(t)$ & $R_i'(t)$ & $R_i(t)$ & $R_i'(t)$" * "\\\\")
        println(io, raw"\midrule")
        for i in eachindex(value)
            cells = [string(i), @sprintf("\$%.3f\$", Float64(value[i])),
                     @sprintf("\$%.4f\$", Float64(derivative[i]))]
            append!(cells, ["\$" * latex_error(err[i], 1) * "\$" for err in errors])
            println(io, join(cells, " & "), "\\\\")
        end
        println(io, raw"\bottomrule")
        println(io, raw"\end{tabular}")
        println(io, raw"\end{center}")
        m = maximum.(errors)
        println(io, "The largest relative errors over the ten voxels are \$", latex_error(m[1]),
                "\$ and \$", latex_error(m[2]), "\$ for CTSE, and \$", latex_error(m[3]),
                "\$ and \$", latex_error(m[4]), "\$ for dual CR, for the temperatures and",
                " derivatives respectively (reference evaluated at 256-bit precision).")
    end
end

function write_comparison(name, method, computed, reference, labels)
    errors = [maximum(abs.(BigFloat.(a) .- b)) for (a, b) in zip(computed, reference)]
    path = joinpath(@__DIR__, "$(name)_comparison.tex")
    open(path, "w") do io
        println(io, "% Generated by verify_ctse_dual_cr_examples.jl; do not edit by hand.")
        println(io, raw"\begin{center}")
        println(io, raw"\begin{tabular}{lcc}")
        println(io, raw"\toprule")
        println(io, "Quantity & $method & Analytical " * "\\\\")
        println(io, raw"\midrule")
        for (row, (label, a, b)) in enumerate(zip(labels, computed, reference))
            row_end = a isa AbstractMatrix ? "\\\\" : raw"\\[4pt]"
            println(io, "\$", label, "\$ & \$", latex_result(a), "\$ & \$", latex_result(b), "\$ " * row_end)
            if a isa AbstractMatrix && row < length(computed)
                println(io, raw"\addlinespace[8pt]")
            end
        end
        println(io, raw"\bottomrule")
        println(io, raw"\end{tabular}")
        println(io, raw"\end{center}")
        # Scalar results that are the correctly rounded references have no error
        # beyond storing the answer in Float64; say so instead of quoting it.
        if all(a isa Number && a == Float64(b) for (a, b) in zip(computed, reference))
            println(io, "Both computed entries equal the analytical values rounded to",
                    " double precision (references evaluated at 256-bit precision).")
        else
            println(io, "The ", computed[1] isa Number ? "absolute errors" : "largest absolute errors among the matrix entries",
                    " are ", raw"$", latex_error(errors[1]), raw"$", " for the value and ",
                    raw"$", latex_error(errors[2]), raw"$", " for the derivative",
                    " (references evaluated at 256-bit precision).")
        end
    end
end

@testset "CTSE and dual CR worked examples" begin
    t0, h = 1.0, 1e-20
    scalar_reference = [sin(1.0), cos(1.0)]

    # Example 1: evaluate the scalar sine at a complex seed.
    ex = run_example("ctse_scalar.jl")
    scalar_ctse = [ex.value, ex.derivative]
    @test scalar_ctse ≈ scalar_reference rtol=1e-13

    # Example 2: a complex matrix sine in the timestep direction H.
    H = [0.0 1.0; -1.0 0.0]
    c, s = cosh(t0), sinh(t0)
    value_reference = [0.0 s; -s 0.0]
    derivative_reference = [0.0 c; -c 0.0]
    ex = run_example("ctse_matrix.jl")
    matrix_ctse_value, matrix_ctse_derivative = ex.value, ex.derivative
    @test matrix_ctse_value ≈ value_reference rtol=1e-13
    @test matrix_ctse_derivative ≈ derivative_reference rtol=1e-13

    # End of Example 2: in the direction I, Julia's complex matrix sine loses the
    # imaginary part, while the real block matrix keeps it. If the first test
    # fails, Julia's sine has changed and the document's discussion is outdated.
    @test iszero(imag.(sin(H + im*h*I)))
    @test sin([H zeros(2, 2); I H])[3:4, 1:2] ≈ cosh(1.0)*Matrix(I, 2, 2) rtol=1e-13

    # Section 3: dual arithmetic by hand gives the value and derivative, but
    # Julia's matrix exponential (behind its matrix sine) has no method for a
    # dual type. If the second test fails, the document's argument is outdated.
    ex = run_example("dual_scalar.jl")
    @test (ex.value, ex.derivative) == (sin(1.0), cos(1.0))
    @test !hasmethod(LinearAlgebra.exp!, Tuple{Matrix{ex.Dual}})

    # Example 3: the scalar seed represented as an ordinary real matrix.
    ex = run_example("dual_cr_scalar.jl")
    scalar_cr = [ex.value, ex.derivative]
    @test scalar_cr ≈ scalar_reference rtol=1e-13
    @test ex.Y ≈ [sin(1.0) 0.0; cos(1.0) sin(1.0)] rtol=1e-13

    # Example 4: the first block column holds value and timestep derivative.
    ex = run_example("dual_cr_matrix.jl")
    matrix_cr_value, matrix_cr_derivative = ex.value, ex.derivative
    @test ex.G ≈ [value_reference zeros(2, 2);
                  derivative_reference value_reference] rtol=1e-13

    # Beyond first derivatives: at order two, block k of the first block column
    # holds F^(k)(1)/k! for F(t) = H*sinh(t).
    T2 = [1.0 0.0 0.0; 1.0 1.0 0.0; 0.0 1.0 1.0]
    G2 = sin(kron(T2, H))
    for (k, block) in enumerate((value_reference, derivative_reference, value_reference/2))
        @test G2[2k-1:2k, 1:2] ≈ block rtol=1e-13
    end

    @printf("Scalar CTSE: value = %.12f, derivative = %.12f\n", scalar_ctse...)
    @printf("Scalar CR:   value = %.12f, derivative = %.12f\n", scalar_cr...)
    for (name, value, derivative) in
        (("CTSE", matrix_ctse_value, matrix_ctse_derivative),
         ("CR", matrix_cr_value, matrix_cr_derivative))
        println("Matrix $name value:")
        show(stdout, "text/plain", value)
        println("\nMatrix $name derivative:")
        show(stdout, "text/plain", derivative)
        println()
    end

    # Verify the link to the actual implementation, including nonzero forcing.
    model = thermal_example()
    (; A, B, x, u, dt) = model
    for e in (model.e, collect(range(0.01, 0.1; length=length(x))))
        ctse = ctse_response(A, B, e, x, u, dt; h)
        cr = oti_response(A, B, e, x, u, dt; order=1)
        reference = analytical_response(A, B, e, x, u, dt; order=1)
        @test ctse.value ≈ reference[:, 1] rtol=1e-11
        @test ctse.derivative ≈ reference[:, 2] rtol=1e-11 atol=1e-12
        @test cr.derivatives ≈ reference rtol=1e-11
        @test cr.derivatives[:, 2] ≈ A*cr.derivatives[:, 1]+B*u+e rtol=1e-11 atol=1e-12
    end

    # Thermal results table: CTSE and first-order CR against a 256-bit reference,
    # which must itself agree with the independent modal solution.
    ex = run_example("thermal.jl")
    ctse, cr = ex.ctse, ex.cr
    big_value, big_derivative = thermal_reference(A, B, model.e, x, u, dt)
    modal = analytical_response(A, B, model.e, x, u, dt; order=1)
    @test Float64.(big_value) ≈ modal[:, 1] rtol=1e-13
    @test Float64.(big_derivative) ≈ modal[:, 2] rtol=1e-12
    write_thermal_comparison(big_value, big_derivative, (ctse.value, ctse.derivative),
                             (cr.derivatives[:, 1], cr.derivatives[:, 2]))

    # Generate each document comparison from the computed results and independent
    # scalar analytical formulas evaluated at higher precision.
    setprecision(BigFloat, 256) do
        scalar_reference = (sin(BigFloat(1)), cos(BigFloat(1)))
        matrix_reference = (BigFloat.(H)*sinh(BigFloat(1)), BigFloat.(H)*cosh(BigFloat(1)))
        scalar_labels = (raw"f(1)=\sin(1)", raw"f'(1)=\cos(1)")
        matrix_labels = (raw"F(1)=H\sinh(1)", raw"F'(1)=H\cosh(1)")
        write_comparison("ctse_scalar", "CTSE", scalar_ctse, scalar_reference, scalar_labels)
        write_comparison("ctse_matrix", "CTSE", (matrix_ctse_value, matrix_ctse_derivative), matrix_reference, matrix_labels)
        write_comparison("dual_cr_scalar", "Dual CR", scalar_cr, scalar_reference, scalar_labels)
        write_comparison("dual_cr_matrix", "Dual CR", (matrix_cr_value, matrix_cr_derivative), matrix_reference, matrix_labels)
    end
end
